// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package kv

type Options struct {
	OnContentChange ContentChange
	OnWatchError    WatchError
}

func (cc *Options) SetOption(opt Option) {
	_ = opt(cc)
}

func (cc *Options) ApplyOption(opts ...Option) {
	for _, opt := range opts {
		_ = opt(cc)
	}
}

func (cc *Options) GetSetOption(opt Option) Option {
	return opt(cc)
}

type Option func(cc *Options) Option

func WithOnContentChange(v ContentChange) Option {
	return func(cc *Options) Option {
		previous := cc.OnContentChange
		cc.OnContentChange = v
		return WithOnContentChange(previous)
	}
}

func WithOnWatchError(v WatchError) Option {
	return func(cc *Options) Option {
		previous := cc.OnWatchError
		cc.OnWatchError = v
		return WithOnWatchError(previous)
	}
}

func NewOptions(opts ...Option) *Options {
	cc := newDefaultOptions()

	for _, opt := range opts {
		_ = opt(cc)
	}
	if watchDogOptions != nil {
		watchDogOptions(cc)
	}
	return cc
}

func InstallOptionsWatchDog(dog func(cc *Options)) {
	watchDogOptions = dog
}

var watchDogOptions func(cc *Options)

func newDefaultOptions() *Options {

	cc := &Options{}

	for _, opt := range [...]Option{
		WithOnContentChange(nil),
		WithOnWatchError(nil),
	} {
		_ = opt(cc)
	}

	return cc
}
