// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

// KType 默认key类型

// SetProviderByFieldType 替换

// ParseKeyFunc val解析，替换

var typeNameSliceUint = ""

// StringValueDelim 数据分割符

func init() {
	v := []uint{}
	typeNameSliceUint = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint, func(valPtr interface{}, stringAlias func(s string) string) flag.Getter {
		return NewSliceUint(valPtr.(*[]uint), stringAlias)
	})
}

// Slice struct
type SliceUint struct {
	stringAlias func(s string) string
	s           *[]uint
	set         bool // if there a flag defined via command line, the slice will be cleared first.
}

// NewSlice new func
func NewSliceUint(p *[]uint, stringAlias func(s string) string) *SliceUint {
	return &SliceUint{
		stringAlias: stringAlias,
		s:           p,
		set:         false,
	}
}

// Set 解析时由FlagSet设定而来，进行解析
func (s *SliceUint) Set(str string) error {
	str = s.stringAlias(str)
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint(s.stringAlias(v))
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

// Get 返回数据
func (s *SliceUint) Get() interface{} {
	return []uint(*s.s)
}

// TypeName type name for vars FlagValue provider
func (s *SliceUint) TypeName() string { return typeNameSliceUint }

// String 获取Set设置的字符串数据？或数据转换到的？
func (s *SliceUint) String() string {
	if s.s == nil || len(*s.s) == 0 {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

// Usage  usage info for FlagSet
func (s *SliceUint) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
