// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var 类型
type Int int

var typeNameInt = ""

func init() {
	var ss int
	typeNameInt = reflect.TypeOf(ss).Name()
}

// NewVar new
func NewInt(p *int) *Int { return (*Int)(p) }

// Set for each of the types
func (f *Int) Set(s string) error {
	v, err := parseInt(s)
	if err != nil {
		return err
	}
	*f = Int(v)
	return nil
}

// TypeName 类型名称
func (f *Int) TypeName() string { return typeNameInt }

// Get 返回类型值
func (f *Int) Get() interface{} { return int(*f) }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Int) String() string { return fmt.Sprintf("%v", *f) }

// Usage FlagSet使用
func (f *Int) Usage() string { return "xconf/xflag/vars" }
