// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceInt = ""

func init() {
	v := []int{}
	typeNameSliceInt = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt, func(valPtr interface{}) flag.Getter {
		return NewSliceInt(valPtr.(*[]int))
	})
}

type SliceInt struct {
	s   *[]int
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceInt(p *[]int) *SliceInt {
	return &SliceInt{
		s:   p,
		set: false,
	}
}

func (s *SliceInt) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceInt) Get() interface{} {
	return []int(*s.s)
}
func (e *SliceInt) TypeName() string { return typeNameSliceInt }
func (s *SliceInt) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceInt) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
