// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type String struct {
	v           *string
	stringAlias func(s string) string
}

var typeNameString = ""

func init() {
	var ss string
	typeNameString = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewString(p *string, stringAlias func(s string) string) *String {
	return &String{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *String) Set(s string) error {
	v, err := parseString(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *String) TypeName() string { return typeNameString }

// Get 返回类型值
func (f *String) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *String) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *String) Usage() string { return "xconf/xflag/vars" }

// IsBoolFlag IsBoolFlag
func (f *String) IsBoolFlag() bool { return typeNameString == "bool" }
