// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceUint64 = ""

func init() {
	v := []uint64{}
	typeNameSliceUint64 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint64, func(valPtr interface{}) flag.Getter {
		return NewSliceUint64(valPtr.(*[]uint64))
	})
}

type SliceUint64 struct {
	s   *[]uint64
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceUint64(p *[]uint64) *SliceUint64 {
	return &SliceUint64{
		s:   p,
		set: false,
	}
}

func (s *SliceUint64) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint64(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceUint64) Get() interface{} {
	return []uint64(*s.s)
}

func (s *SliceUint64) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceUint64) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars %s,v%sv%sv", typeNameSliceUint64, StringValueDelim, StringValueDelim)
}
