// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceStrig = ""

func init() {
	v := []string{}
	typeNameSliceStrig = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceStrig, func(valPtr interface{}) flag.Getter {
		return NewSliceStrig(valPtr.(*[]string))
	})
}

type SliceStrig struct {
	s   *[]string
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceStrig(p *[]string) *SliceStrig {
	return &SliceStrig{
		s:   p,
		set: false,
	}
}

func (s *SliceStrig) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseString(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceStrig) Get() interface{} {
	return []string(*s.s)
}
func (e *SliceStrig) TypeName() string { return typeNameSliceStrig }
func (s *SliceStrig) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceStrig) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
