// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceInt32 = ""

func init() {
	v := []int32{}
	typeNameSliceInt32 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt32, func(valPtr interface{}) flag.Getter {
		return NewSliceInt32(valPtr.(*[]int32))
	})
}

type SliceInt32 struct {
	s   *[]int32
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceInt32(p *[]int32) *SliceInt32 {
	return &SliceInt32{
		s:   p,
		set: false,
	}
}

func (s *SliceInt32) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt32(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceInt32) Get() interface{} {
	return []int32(*s.s)
}

func (s *SliceInt32) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceInt32) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars %s,v%sv%sv", typeNameSliceInt32, StringValueDelim, StringValueDelim)
}
