// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

// KType 默认key类型

// SetProviderByFieldType 替换

// ParseKeyFunc val解析，替换

var typeNameSliceUint64 = ""

// StringValueDelim 数据分割符

func init() {
	v := []uint64{}
	typeNameSliceUint64 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint64, func(valPtr interface{}) flag.Getter {
		return NewSliceUint64(valPtr.(*[]uint64))
	})
}

// Slice struct
type SliceUint64 struct {
	s   *[]uint64
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

// NewSlice new func
func NewSliceUint64(p *[]uint64) *SliceUint64 {
	return &SliceUint64{
		s:   p,
		set: false,
	}
}

// Set 解析时由FlagSet设定而来，进行解析
func (s *SliceUint64) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint64(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

// Get 返回数据
func (s *SliceUint64) Get() interface{} {
	return []uint64(*s.s)
}

// TypeName type name for vars FlagValue provider
func (s *SliceUint64) TypeName() string { return typeNameSliceUint64 }

// String 获取Set设置的字符串数据？或数据转换到的？
func (s *SliceUint64) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

// Usage  usage info for FlagSet
func (s *SliceUint64) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
