// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceUint8 = ""

func init() {
	v := []uint8{}
	typeNameSliceUint8 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint8, func(valPtr interface{}) flag.Getter {
		return NewSliceUint8(valPtr.(*[]uint8))
	})
}

type SliceUint8 struct {
	s   *[]uint8
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceUint8(p *[]uint8) *SliceUint8 {
	return &SliceUint8{
		s:   p,
		set: false,
	}
}

func (s *SliceUint8) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint8(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceUint8) Get() interface{} {
	return []uint8(*s.s)
}
func (e *SliceUint8) TypeName() string { return typeNameSliceUint8 }
func (s *SliceUint8) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceUint8) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
