// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceUint32 = ""

func init() {
	v := []uint32{}
	typeNameSliceUint32 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint32, func(valPtr interface{}) flag.Getter {
		return NewSliceUint32(valPtr.(*[]uint32))
	})
}

type SliceUint32 struct {
	s   *[]uint32
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceUint32(p *[]uint32) *SliceUint32 {
	return &SliceUint32{
		s:   p,
		set: false,
	}
}

func (s *SliceUint32) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint32(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceUint32) Get() interface{} {
	return []uint32(*s.s)
}
func (e *SliceUint32) TypeName() string { return typeNameSliceUint32 }
func (s *SliceUint32) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceUint32) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
