// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"errors"
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type MapKTypeVType(KType,VType,ParseKeyFunc,ParseValFunc,SetProviderByFieldType,StringValueDelim)

var typeNameMapIntString = ""

func init() {
	v := map[int]string{}
	typeNameMapIntString = fmt.Sprintf("map[%s]%s", reflect.TypeOf(v).Key().Name(), reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameMapIntString, func(valPtr interface{}) flag.Getter {
		return NewMapIntString(valPtr)
	})
}

type MapIntString struct {
	s   string
	set bool
	val *map[int]string
}

func NewMapIntString(valPtr interface{}) *MapIntString {
	return &MapIntString{
		val: valPtr.(*map[int]string),
	}
}

func (e *MapIntString) Get() interface{} {
	vv := make(map[string]interface{})
	for k, v := range *e.val {
		vv[fmt.Sprintf("%v", k)] = v
	}
	return vv
}

// Usage  usage info for FlagSet
func (e *MapIntString) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, key and value split by %s", StringValueDelim)
}

// TypeName type name for vars FlagValue provider
func (e *MapIntString) TypeName() string { return typeNameMapIntString }
func (e *MapIntString) String() string   { return e.s }
func (e *MapIntString) Set(s string) error {
	e.s = s
	kv := strings.Split(s, StringValueDelim)
	if len(kv)%2 == 1 {
		return errors.New("got the odd number of input pairs")
	}
	if !e.set {
		e.set = true
		*e.val = make(map[int]string)
	}
	var key string
	for i, s := range kv {
		if i%2 == 0 {
			key = s
			continue
		}
		keyVal, err := parseInt(key)
		if err != nil {
			return err
		}
		val, err := parseString(s)
		if err != nil {
			return err
		}
		(*e.val)[keyVal] = val
	}
	return nil
}
