// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Uint64 uint64

var typeNameUint64 = ""

func init() {
	var ss uint64
	typeNameUint64 = reflect.TypeOf(ss).Name()
}
func NewUint64(p *uint64) *Uint64 { return (*Uint64)(p) }

// Setters for each of the types
func (f *Uint64) Set(s string) error {
	v, err := parseUint64(s)
	if err != nil {
		return err
	}
	*f = Uint64(v)
	return nil
}
func (f *Uint64) TypeName() string { return typeNameUint64 }
func (f *Uint64) Get() interface{} { return uint64(*f) }
func (f *Uint64) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Uint64) Usage() string    { return "xconf/xflag/vars" }
