// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Uint8 uint8

var typeNameUint8 = ""

func init() {
	var ss uint8
	typeNameUint8 = reflect.TypeOf(ss).Name()
}
func NewUint8(p *uint8) *Uint8 { return (*Uint8)(p) }

// Setters for each of the types
func (f *Uint8) Set(s string) error {
	v, err := parseUint8(s)
	if err != nil {
		return err
	}
	*f = Uint8(v)
	return nil
}
func (f *Uint8) TypeName() string { return typeNameUint8 }
func (f *Uint8) Get() interface{} { return uint8(*f) }
func (f *Uint8) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Uint8) Usage() string    { return "xconf/xflag/vars" }
