// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"errors"
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type MapKTypeVType(KType,VType,ParseKeyFunc,ParseValFunc,SetProviderByFieldType,StringValueDelim)
// KType 默认key类型

// VType 默认val类型

// StringValueDelim 数据分割符

// SetProviderByFieldType 替换

// ParseKeyFunc key解析，替换

// ParseValFunc val解析，替换

var typeNameMapIntInt = ""

func init() {
	v := map[int]int{}
	typeNameMapIntInt = fmt.Sprintf("map[%s]%s", reflect.TypeOf(v).Key().Name(), reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameMapIntInt, func(valPtr interface{}) flag.Getter {
		return NewMapIntInt(valPtr)
	})
}

// MapKTypeVType
type MapIntInt struct {
	s   string
	set bool
	val *map[int]int
}

// NewMapKTypeVType 创建指定类型
func NewMapIntInt(valPtr interface{}) *MapIntInt {
	return &MapIntInt{
		val: valPtr.(*map[int]int),
	}
}

// Get 返回数据，必须返回map[string]interface{}类型
func (e *MapIntInt) Get() interface{} {
	vv := make(map[string]interface{})
	for k, v := range *e.val {
		vv[fmt.Sprintf("%v", k)] = v
	}
	return vv
}

// Usage  usage info for FlagSet
func (e *MapIntInt) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, key and value split by %s", StringValueDelim)
}

// TypeName type name for vars FlagValue provider
func (e *MapIntInt) TypeName() string { return typeNameMapIntInt }

// String 获取Set设置的字符串数据？或数据转换到的？
func (e *MapIntInt) String() string { return e.s }

// Set 解析时由FlagSet设定而来，进行解析
func (e *MapIntInt) Set(s string) error {
	e.s = s
	kv := strings.Split(s, StringValueDelim)
	if len(kv)%2 == 1 {
		return errors.New("got the odd number of input pairs")
	}
	if !e.set {
		e.set = true
		*e.val = make(map[int]int)
	}
	var key string
	for i, s := range kv {
		if i%2 == 0 {
			key = s
			continue
		}
		keyVal, err := parseInt(key)
		if err != nil {
			return err
		}
		val, err := parseInt(s)
		if err != nil {
			return err
		}
		(*e.val)[keyVal] = val
	}
	return nil
}
