// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)
// KType 默认key类型

// SetProviderByFieldType 替换

// ParseKeyFunc val解析，替换

var typeNameSliceUint16 = ""

func init() {
	v := []uint16{}
	typeNameSliceUint16 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceUint16, func(valPtr interface{}) flag.Getter {
		return NewSliceUint16(valPtr.(*[]uint16))
	})
}

// Slice
type SliceUint16 struct {
	s   *[]uint16
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

// NewSlice 创建指定类型
func NewSliceUint16(p *[]uint16) *SliceUint16 {
	return &SliceUint16{
		s:   p,
		set: false,
	}
}

// Set 解析时由FlagSet设定而来，进行解析
func (s *SliceUint16) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseUint16(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

// Get 返回数据
func (s *SliceUint16) Get() interface{} {
	return []uint16(*s.s)
}

// TypeName type name for vars FlagValue provider
func (e *SliceUint16) TypeName() string { return typeNameSliceUint16 }

// String 获取Set设置的字符串数据？或数据转换到的？
func (s *SliceUint16) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

// Usage  usage info for FlagSet
func (s *SliceUint16) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
