// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)
// KType 默认key类型

// SetProviderByFieldType 替换

// ParseKeyFunc val解析，替换

var typeNameSliceInt32 = ""

func init() {
	v := []int32{}
	typeNameSliceInt32 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt32, func(valPtr interface{}) flag.Getter {
		return NewSliceInt32(valPtr.(*[]int32))
	})
}

// Slice
type SliceInt32 struct {
	s   *[]int32
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

// NewSlice 创建指定类型
func NewSliceInt32(p *[]int32) *SliceInt32 {
	return &SliceInt32{
		s:   p,
		set: false,
	}
}

// Set 解析时由FlagSet设定而来，进行解析
func (s *SliceInt32) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt32(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

// Get 返回数据
func (s *SliceInt32) Get() interface{} {
	return []int32(*s.s)
}

// TypeName type name for vars FlagValue provider
func (e *SliceInt32) TypeName() string { return typeNameSliceInt32 }

// String 获取Set设置的字符串数据？或数据转换到的？
func (s *SliceInt32) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

// Usage  usage info for FlagSet
func (s *SliceInt32) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
