// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"errors"
	"flag"
	"fmt"
	"reflect"
	"strings"
	"time"
)

//template type MapKTypeVType(KType,VType,ParseKeyFunc,ParseValFunc,SetProviderByFieldType,StringValueDelim)

var typeNameMapStringTimeDuration = ""

func init() {
	v := map[string]time.Duration{}
	typeNameMapStringTimeDuration = fmt.Sprintf("map[%s]%s", reflect.TypeOf(v).Key().Name(), reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameMapStringTimeDuration, func(valPtr interface{}) flag.Getter {
		return NewMapStringTimeDuration(valPtr)
	})
}

type MapStringTimeDuration struct {
	s   string
	set bool
	val *map[string]time.Duration
}

func NewMapStringTimeDuration(valPtr interface{}) *MapStringTimeDuration {
	return &MapStringTimeDuration{
		val: valPtr.(*map[string]time.Duration),
	}
}

func (e *MapStringTimeDuration) Get() interface{} {
	vv := make(map[string]interface{})
	for k, v := range *e.val {
		vv[fmt.Sprintf("%v", k)] = v
	}
	return vv
}
func (e *MapStringTimeDuration) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars %s,k%sv%sk%sv", typeNameMapStringTimeDuration, StringValueDelim, StringValueDelim, StringValueDelim)
}
func (e *MapStringTimeDuration) String() string { return e.s }
func (e *MapStringTimeDuration) Set(s string) error {
	e.s = s
	kv := strings.Split(s, StringValueDelim)
	if len(kv)%2 == 1 {
		return errors.New("got the odd number of input pairs")
	}
	if !e.set {
		e.set = true
		*e.val = make(map[string]time.Duration)
	}
	var key string
	for i, s := range kv {
		if i%2 == 0 {
			key = s
			continue
		}
		keyVal, err := parseString(key)
		if err != nil {
			return err
		}
		val, err := parseTimeDuration(s)
		if err != nil {
			return err
		}
		(*e.val)[keyVal] = val
	}
	return nil
}
