// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
	"time"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Duration struct {
	v           *time.Duration
	stringAlias func(s string) string
}

var typeNameDuration = ""

func init() {
	var ss time.Duration
	typeNameDuration = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewDuration(p *time.Duration, stringAlias func(s string) string) *Duration {
	return &Duration{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Duration) Set(s string) error {
	v, err := parseTimeDuration(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Duration) TypeName() string { return typeNameDuration }

// Get 返回类型值
func (f *Duration) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Duration) String() string { return fmt.Sprintf("%v", *f.v) }

// Usage FlagSet使用
func (f *Duration) Usage() string { return "xconf/xflag/vars" }
