// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Int64 int64

func NewInt64(p *int64) *Int64 { return (*Int64)(p) }

// Setters for each of the types
func (f *Int64) Set(s string) error {
	v, err := parseInt64(s)
	if err != nil {
		return err
	}
	*f = Int64(v)
	return nil
}
func (f *Int64) Get() interface{} { return int64(*f) }
func (f *Int64) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Int64) Usage() string    { return fmt.Sprintf("xconf/xflag/vars %s", reflect.TypeOf(*f)) }
