// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Int int

var typeNameInt = ""

func init() {
	var ss int
	typeNameInt = reflect.TypeOf(ss).Name()
}
func NewInt(p *int) *Int { return (*Int)(p) }

// Setters for each of the types
func (f *Int) Set(s string) error {
	v, err := parseInt(s)
	if err != nil {
		return err
	}
	*f = Int(v)
	return nil
}
func (f *Int) TypeName() string { return typeNameInt }
func (f *Int) Get() interface{} { return int(*f) }
func (f *Int) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Int) Usage() string    { return "xconf/xflag/vars" }
