// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var 类型
type Int64 int64

var typeNameInt64 = ""

func init() {
	var ss int64
	typeNameInt64 = reflect.TypeOf(ss).Name()
}

// NewVar new
func NewInt64(p *int64) *Int64 { return (*Int64)(p) }

// Set for each of the types
func (f *Int64) Set(s string) error {
	v, err := parseInt64(s)
	if err != nil {
		return err
	}
	*f = Int64(v)
	return nil
}

// TypeName 类型名称
func (f *Int64) TypeName() string { return typeNameInt64 }

// Get 返回类型值
func (f *Int64) Get() interface{} { return int64(*f) }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Int64) String() string { return fmt.Sprintf("%v", *f) }

// Usage FlagSet使用
func (f *Int64) Usage() string { return "xconf/xflag/vars" }
