// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Bool struct {
	v           *bool
	stringAlias func(s string) string
}

var typeNameBool = ""

func init() {
	var ss bool
	typeNameBool = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewBool(p *bool, stringAlias func(s string) string) *Bool {
	return &Bool{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Bool) Set(s string) error {
	v, err := parseBool(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Bool) TypeName() string { return typeNameBool }

// Get 返回类型值
func (f *Bool) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Bool) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *Bool) Usage() string { return "xconf/xflag/vars" }
