// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
	"time"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Time struct {
	v           *time.Time
	stringAlias func(s string) string
}

var typeNameTime = ""

func init() {
	var ss time.Time
	typeNameTime = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewTime(p *time.Time, stringAlias func(s string) string) *Time {
	return &Time{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Time) Set(s string) error {
	v, err := parseTime(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Time) TypeName() string { return typeNameTime }

// Get 返回类型值
func (f *Time) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Time) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *Time) Usage() string { return "xconf/xflag/vars" }

// IsBoolFlag IsBoolFlag
func (f *Time) IsBoolFlag() bool { return typeNameTime == "bool" }
