// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Uint64 struct {
	v           *uint64
	stringAlias func(s string) string
}

var typeNameUint64 = ""

func init() {
	var ss uint64
	typeNameUint64 = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewUint64(p *uint64, stringAlias func(s string) string) *Uint64 {
	return &Uint64{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Uint64) Set(s string) error {
	v, err := parseUint64(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Uint64) TypeName() string { return typeNameUint64 }

// Get 返回类型值
func (f *Uint64) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Uint64) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *Uint64) Usage() string { return "xconf/xflag/vars" }

// IsBoolFlag IsBoolFlag
func (f *Uint64) IsBoolFlag() bool { return typeNameUint64 == "bool" }
