// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceInt64 = ""

func init() {
	v := []int64{}
	typeNameSliceInt64 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt64, func(valPtr interface{}) flag.Getter {
		return NewSliceInt64(valPtr.(*[]int64))
	})
}

type SliceInt64 struct {
	s   *[]int64
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceInt64(p *[]int64) *SliceInt64 {
	return &SliceInt64{
		s:   p,
		set: false,
	}
}

func (s *SliceInt64) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt64(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceInt64) Get() interface{} {
	return []int64(*s.s)
}

func (s *SliceInt64) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceInt64) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars %s,v%sv%sv", typeNameSliceInt64, StringValueDelim, StringValueDelim)
}
