// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceInt16 = ""

func init() {
	v := []int16{}
	typeNameSliceInt16 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt16, func(valPtr interface{}) flag.Getter {
		return NewSliceInt16(valPtr.(*[]int16))
	})
}

type SliceInt16 struct {
	s   *[]int16
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceInt16(p *[]int16) *SliceInt16 {
	return &SliceInt16{
		s:   p,
		set: false,
	}
}

func (s *SliceInt16) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt16(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceInt16) Get() interface{} {
	return []int16(*s.s)
}
func (e *SliceInt16) TypeName() string { return typeNameSliceInt16 }
func (s *SliceInt16) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceInt16) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
