// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Int struct {
	v           *int
	stringAlias func(s string) string
}

var typeNameInt = ""

func init() {
	var ss int
	typeNameInt = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewInt(p *int, stringAlias func(s string) string) *Int {
	return &Int{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Int) Set(s string) error {
	v, err := parseInt(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Int) TypeName() string { return typeNameInt }

// Get 返回类型值
func (f *Int) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Int) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *Int) Usage() string { return "xconf/xflag/vars" }
