// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceInt8 = ""

func init() {
	v := []int8{}
	typeNameSliceInt8 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceInt8, func(valPtr interface{}) flag.Getter {
		return NewSliceInt8(valPtr.(*[]int8))
	})
}

type SliceInt8 struct {
	s   *[]int8
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceInt8(p *[]int8) *SliceInt8 {
	return &SliceInt8{
		s:   p,
		set: false,
	}
}

func (s *SliceInt8) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseInt8(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceInt8) Get() interface{} {
	return []int8(*s.s)
}
func (e *SliceInt8) TypeName() string { return typeNameSliceInt8 }
func (s *SliceInt8) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceInt8) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
