// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
	"time"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceTimeDuration = ""

func init() {
	v := []time.Duration{}
	typeNameSliceTimeDuration = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceTimeDuration, func(valPtr interface{}) flag.Getter {
		return NewSliceTimeDuration(valPtr.(*[]time.Duration))
	})
}

type SliceTimeDuration struct {
	s   *[]time.Duration
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceTimeDuration(p *[]time.Duration) *SliceTimeDuration {
	return &SliceTimeDuration{
		s:   p,
		set: false,
	}
}

func (s *SliceTimeDuration) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseTimeDuration(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceTimeDuration) Get() interface{} {
	return []time.Duration(*s.s)
}
func (e *SliceTimeDuration) TypeName() string { return typeNameSliceTimeDuration }
func (s *SliceTimeDuration) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceTimeDuration) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
