// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var type
type Int32 struct {
	v           *int32
	stringAlias func(s string) string
}

var typeNameInt32 = ""

func init() {
	var ss int32
	typeNameInt32 = reflect.TypeOf(ss).Name()
}

// NewVar new func
func NewInt32(p *int32, stringAlias func(s string) string) *Int32 {
	return &Int32{
		v:           p,
		stringAlias: stringAlias,
	}
}

// Set for each of the types
func (f *Int32) Set(s string) error {
	v, err := parseInt32(f.stringAlias(s))
	if err != nil {
		return err
	}
	*f.v = v
	return nil
}

// TypeName 类型名称
func (f *Int32) TypeName() string { return typeNameInt32 }

// Get 返回类型值
func (f *Int32) Get() interface{} { return *f.v }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Int32) String() string {
	if f.v == nil {
		return ""
	}
	return fmt.Sprintf("%v", *f.v)
}

// Usage FlagSet使用
func (f *Int32) Usage() string { return "xconf/xflag/vars" }
