// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Uint16 uint16

var typeNameUint16 = ""

func init() {
	var ss uint16
	typeNameUint16 = reflect.TypeOf(ss).Name()
}
func NewUint16(p *uint16) *Uint16 { return (*Uint16)(p) }

// Setters for each of the types
func (f *Uint16) Set(s string) error {
	v, err := parseUint16(s)
	if err != nil {
		return err
	}
	*f = Uint16(v)
	return nil
}
func (f *Uint16) TypeName() string { return typeNameUint16 }
func (f *Uint16) Get() interface{} { return uint16(*f) }
func (f *Uint16) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Uint16) Usage() string    { return "xconf/xflag/vars" }
