// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"flag"
	"fmt"
	"reflect"
	"strings"
)

//template type Slice(KType,ParseKeyFunc,SetProviderByFieldType,StringValueDelim)

var typeNameSliceFloat64 = ""

func init() {
	v := []float64{}
	typeNameSliceFloat64 = fmt.Sprintf("[]%s", reflect.TypeOf(v).Elem().Name())
	SetProviderByFieldType(typeNameSliceFloat64, func(valPtr interface{}) flag.Getter {
		return NewSliceFloat64(valPtr.(*[]float64))
	})
}

type SliceFloat64 struct {
	s   *[]float64
	set bool // if there a flag defined via command line, the slice will be cleared first.
}

func NewSliceFloat64(p *[]float64) *SliceFloat64 {
	return &SliceFloat64{
		s:   p,
		set: false,
	}
}

func (s *SliceFloat64) Set(str string) error {
	for _, v := range strings.Split(str, StringValueDelim) {
		got, err := parseFloat64(v)
		if err != nil {
			return err
		}
		if !s.set {
			*s.s = (*s.s)[:0]
			s.set = true
		}
		*s.s = append(*s.s, got)
	}
	return nil
}

func (s *SliceFloat64) Get() interface{} {
	return []float64(*s.s)
}
func (e *SliceFloat64) TypeName() string { return typeNameSliceFloat64 }
func (s *SliceFloat64) String() string {
	if s.s == nil {
		return ""
	}
	return fmt.Sprintf("%v", *s.s)
}

func (s *SliceFloat64) Usage() string {
	return fmt.Sprintf("xconf/xflag/vars, value split by %s", StringValueDelim)
}
