// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Float32 float32

func NewFloat32(p *float32) *Float32 { return (*Float32)(p) }

// Setters for each of the types
func (f *Float32) Set(s string) error {
	v, err := parseFloat32(s)
	if err != nil {
		return err
	}
	*f = Float32(v)
	return nil
}
func (f *Float32) Get() interface{} { return float32(*f) }
func (f *Float32) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Float32) Usage() string    { return fmt.Sprintf("xconf/xflag/vars %s", reflect.TypeOf(*f)) }
