// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

// ParseKeyFunc 默认解析函数，替换

// KType 默认类型，替换

// Var 类型
type Float64 float64

var typeNameFloat64 = ""

func init() {
	var ss float64
	typeNameFloat64 = reflect.TypeOf(ss).Name()
}

// NewVar new
func NewFloat64(p *float64) *Float64 { return (*Float64)(p) }

// Set for each of the types
func (f *Float64) Set(s string) error {
	v, err := parseFloat64(s)
	if err != nil {
		return err
	}
	*f = Float64(v)
	return nil
}

// TypeName 类型名称
func (f *Float64) TypeName() string { return typeNameFloat64 }

// Get 返回类型值
func (f *Float64) Get() interface{} { return float64(*f) }

// String 获取Set设置的字符串数据？或数据转换到的？
func (f *Float64) String() string { return fmt.Sprintf("%v", *f) }

// Usage FlagSet使用
func (f *Float64) Usage() string { return "xconf/xflag/vars" }
