// Code generated by gotemplate. DO NOT EDIT.

package vars

import (
	"fmt"
	"reflect"
)

//template type Var(KType,ParseKeyFunc)

type Int32 int32

func NewInt32(p *int32) *Int32 { return (*Int32)(p) }

// Setters for each of the types
func (f *Int32) Set(s string) error {
	v, err := parseInt32(s)
	if err != nil {
		return err
	}
	*f = Int32(v)
	return nil
}
func (f *Int32) Get() interface{} { return int32(*f) }
func (f *Int32) String() string   { return fmt.Sprintf("%v", *f) }
func (f *Int32) Usage() string    { return fmt.Sprintf("xconf/xflag/vars %s", reflect.TypeOf(*f)) }
